version: 2.1
orbs:
  android: circleci/android@3.0.0
  node: circleci/node@7.0.0
jobs:
  build:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install Maestro
          command: curl -Ls "https://get.maestro.mobile.dev" | bash
      - android/create_avd:
          avd_name: myavd
          install: true
          system_image: system-images;android-31;default;x86_64
      - android/start_emulator:
          avd_name: myavd
          no_window: true
          restore_gradle_cache_prefix: v1a
      - run:
          name: Run Maestro Tests
          command: maestro test maestro/login.yaml
