version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30
        environment:
          ANDROID_HOME: /opt/android/sdk
      - image: cimg/node:23.6.1
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: |
            npm install -g yarn
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install Maestro
          command: curl -Ls "https://get.maestro.mobile.dev" | bash
      - run:
          name: Start Emulator
          command: |
            sdkmanager "system-images;android-30;google_apis;x86_64"
            echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"
            $ANDROID_HOME/emulator/emulator -avd test -no-skin -no-audio -no-window &
            adb wait-for-device
      - run:
          name: Run Maestro Tests
          command: maestro test maestro/login.yaml
