version: 2.1
orbs:
  android: circleci/android@3.1.0
commands:
  install_node_modules:
    steps:
      - run:
          name: Install Node Modules
          command: yarn
  install_maestro_cli:
    steps:
      - run:
          name: Install Maestro CLI
          command: |
            curl -Ls "https://get.maestro.mobile.dev" | bash
            echo 'export PATH="$HOME/.maestro/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
  install_gems:
    steps:
      - run:
          name: Install Gems
          command: |
            rbenv install
            gem install bundler:2.5.3
            bundle install
  run-maestro-tests:
    description: Run Maestro Tests
    parameters:
      platform:
        type: enum
        enum:
          - android
        description: Platform to run the tests for
      maestro_file:
        type: string
        description: Path to the Maestro test file
    steps:
      - run:
          name: Run Maestro Tests for << parameters.platform >>
          command: |
            maestro test << parameters.maestro_file >>
            MAESTRO_STATUS=$?
            if [ "$MAESTRO_STATUS" -eq 0 ]; then
                echo "✅ Tests Passed"
            else
                echo "❌ Tests Failed"
            fi
jobs:
  run_maestro_android:
    docker:
      - image: 'cimg/android:2025.04-node'
    resource_class: large
    working_directory: ~/project
    steps:
      - checkout
      - install_node_modules
      - install_maestro_cli
      - run:
          name: Build Android App
          command: |
            cd android
            ./gradlew assembleExperimentalDebug --no-daemon --console=plain
      - store_artifacts:
          path: ./android/app/build/outputs/apk/experimental/debug/app-experimental-debug.apk
      - run-maestro-tests:
          platform: android
          maestro_file: .maestro/login.yml
workflows:
  version: 2
  maestro_tests:
    jobs:
      - run_maestro_android