name: Run Maestro Tests on Android

on:
  pull_request:
    branches:
      - '*'

jobs:
  android-maestro-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Android Emulator and Run Maestro Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          ram-size: 2048M
          disk-size: 4096M
          target: playstore
          script: |
            avdmanager list device