name: Format Code with Prettier

on:
  push:
    branches:
      - '*'
      - '!develop'
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Debug Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "Base ref: ${{ github.base_ref }}"
          echo "Ref: ${{ github.ref }}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request && github.event.pull_request.head.ref || github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier
        run: yarn prettier --write .

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No code format changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Code format changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Get current branch name
        if: steps.check_changes.outputs.changes == 'true'
        id: branch
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: format code with Prettier"
          git push origin HEAD:${{ steps.branch.outputs.branch }}