name: Maestro Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  android-maestro-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download APK
        run: |
          curl -L https://pub-c6a557891e1a4fcdbcd530afab927625.r2.dev/app-experimental-debug.apk -o app-experimental-debug.apk
      
      - name: Check file type
        run: |
          file app-experimental-debug.apk

      - uses: dniHze/maestro-test-action@v1
        with:
          screenshot-dir: screenshots
          report: maestro/report.xml
          version: 1.40.3

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Start Android Emulator and Run Maestro Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          ram-size: 4096M
          disk-size: 4096M
          profile: Nexus 6
          script: |
            mkdir recording
            adb install app-experimental-debug.apk
            maestro test .maestro --format junit --output maestro-report.xml
            maestro hierarchy

      - name: Upload Recordings
        uses: actions/upload-artifact@v4
        with:
          name: Test Recordings
          path: recording
        